[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
aws-iam-authenticator = "latest"
bat = "latest"
delta = "latest"
dotnet = "10"
eza = "latest"
fd = "latest"
fzf = "latest"
git-lfs = "latest"
github-cli = "latest"
"github:luarocks/luarocks" = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
granted = "latest"
jq = "latest"
k6 = "latest"
k9s = "latest"
lazygit = "latest"
lua-language-server = "latest"
mani = "latest"
neovim = "latest"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@angular/language-server" = ["latest", "19"]
"npm:@github/copilot" = ["prerelease", "latest"]
"npm:@github/copilot-language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
opencode = "latest"
python = "3.6"
ripgrep = "latest"
rust = "latest"
shfmt = "latest"
stylua = "latest"
vault = "latest"
zoxide = "latest"
