[tools]
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:hashicorp/vault" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:ripgrep" = "latest"
"cargo:stylua" = "latest"
"cargo:zoxide" = "latest"
"github:anomalyco/opencode" = "latest"
"github:cli/cli" = "latest"
"github:fwdcloudsec/granted" = "latest"
"github:git-lfs/git-lfs" = "latest"
"github:grafana/k6" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:kubernetes-sigs/aws-iam-authenticator" = "latest"
"github:luarocks/luarocks" = "latest"
"github:neovim/neovim" = "latest"
go = "latest"
"go:github.com/alajmo/mani" = "latest"
"go:github.com/derailed/k9s" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:mvdan.cc/sh/v3/cmd/shfmt" = "latest"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@angular/language-server" = ["latest", "19"]
"npm:@github/copilot" = ["prerelease", "latest"]
"npm:@github/copilot-language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
rust = "latest"
