[tools]
cargo = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:git-delta" = "latest"
"cargo:zoxide" = "latest"
fzf = "latest"
"github:BurntSushi/ripgrep" = "latest"
"github:cli/cli" = "latest"
"github:luarocks/luarocks" = "latest"
"github:neovim/neovim" = "latest"
go = "latest"
"go:github.com/alajmo/mani" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
jq = "latest"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "latest"
