[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
aws-iam-authenticator = "latest"
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
git-lfs = "latest"
github-cli = "latest"
"github:luarocks/luarocks" = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
granted = "latest"
jq = "latest"
k6 = "latest"
k9s = "latest"
lazygit = "latest"
mani = "latest"
neovim = "latest"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "latest"
ripgrep = "latest"
vault = "latest"
zoxide = "latest"
