[tools]
bat = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
github-cli = "latest"
"github:luarocks/luarocks" = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
jq = "latest"
lazygit = "latest"
mani = "latest"
neovim = "latest"
node = "24"
"npm:@angular/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "latest"
ripgrep = "latest"
zoxide = "latest"
